In [17]:
import numpy as np

In [18]:
v = [0.5, 0.75, 1.0, 1.5, 2.0]

In [19]:
m = [v,v,v]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [20]:
m[1][0]

0.5

In [21]:
from copy import deepcopy

In [22]:
import array

In [23]:
a = array.array('f', v) # float
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0])

In [24]:
a.extend([5.0, 6.75])
a.tolist()

[0.5, 0.75, 1.0, 1.5, 2.0, 5.0, 6.75]

In [25]:
f = open('array.apy', 'wb')
a.tofile(f)
f.close()

In [26]:
with open('array.apy', 'wb') as f:
    a.tofile(f)

In [27]:
b = array.array('f')

In [28]:
with open('array.apy', 'rb') as f:
    b.fromfile(f,5) # 5 elements

In [29]:
a = np.array([0, 0.5, 1.0, 1.5, 2.0])
a

array([0. , 0.5, 1. , 1.5, 2. ])

In [30]:
type(a)

numpy.ndarray

In [31]:
a = np.arange(2,20,2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
a[5:]

array([12, 14, 16, 18])

In [33]:
a.sum()

90

In [34]:
a.std() # 標準偏差

5.163977794943222

In [35]:
a.cumsum() # 累積和

array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])

In [36]:
a * 2

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36])

In [38]:
b = a.tolist()
b * 2

[2, 4, 6, 8, 10, 12, 14, 16, 18, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [41]:
c = np.array([a, a*2])
c

array([[ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36]])

In [44]:
c[0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [45]:
c[0,2]

6

In [48]:
c[:,1]

array([4, 8])

In [49]:
c.sum()

270

In [51]:
c.sum(axis=0)

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [52]:
c.sum(axis=1)

array([ 90, 180])

In [54]:
d = np.zeros((2,3))
d

array([[0., 0., 0.],
       [0., 0., 0.]])

In [55]:
d = np.ones((2,3))
d

array([[1., 1., 1.],
       [1., 1., 1.]])

In [57]:
d = np.ones_like((2,3))
d

array([1, 1])

In [60]:
e = np.empty((2,3))
e

array([[1., 1., 1.],
       [1., 1., 1.]])

In [62]:
f = np.eye(5)
f

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [65]:
g = np.linspace(5,15,12)
g

array([ 5.        ,  5.90909091,  6.81818182,  7.72727273,  8.63636364,
        9.54545455, 10.45454545, 11.36363636, 12.27272727, 13.18181818,
       14.09090909, 15.        ])

In [66]:
g.size

12

In [69]:
g.itemsize # 1要素のバイト数

8

In [70]:
g.ndim

1

In [75]:
g = np.arange(15)
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [77]:
h = g.reshape((3,5))
h

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [78]:
h.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [79]:
h.transpose()

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [80]:
n = np.resize(g, (5,4))
n

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14,  0],
       [ 1,  2,  3,  4]])

In [82]:
h

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [86]:
# stacking
np.hstack((h, 2*h))

array([[ 0,  1,  2,  3,  4,  0,  2,  4,  6,  8],
       [ 5,  6,  7,  8,  9, 10, 12, 14, 16, 18],
       [10, 11, 12, 13, 14, 20, 22, 24, 26, 28]])

In [87]:
np.vstack((h, 0.5*h))

array([[ 0. ,  1. ,  2. ,  3. ,  4. ],
       [ 5. ,  6. ,  7. ,  8. ,  9. ],
       [10. , 11. , 12. , 13. , 14. ],
       [ 0. ,  0.5,  1. ,  1.5,  2. ],
       [ 2.5,  3. ,  3.5,  4. ,  4.5],
       [ 5. ,  5.5,  6. ,  6.5,  7. ]])

In [88]:
h.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [89]:
h.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [91]:
h > 8

array([[False, False, False, False, False],
       [False, False, False, False,  True],
       [ True,  True,  True,  True,  True]])

In [92]:
(h>8).astype(int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [94]:
np.where(h>8,1,0)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [95]:
np.where(h%2==0,'even', 'false')

array([['even', 'false', 'even', 'false', 'even'],
       ['false', 'even', 'false', 'even', 'false'],
       ['even', 'false', 'even', 'false', 'even']], dtype='|S5')

In [97]:
# Vectorizing

In [101]:
np.random.seed(100)
r = np.arange(12).reshape((4,3))
s = np.arange(12).reshape((4,3)) * 0.5

In [102]:
r

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [103]:
s

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ],
       [4.5, 5. , 5.5]])

In [104]:
r + s

array([[ 0. ,  1.5,  3. ],
       [ 4.5,  6. ,  7.5],
       [ 9. , 10.5, 12. ],
       [13.5, 15. , 16.5]])

In [107]:
#  Memory

In [108]:
x = np.random.standard_normal((1000000, 5))
y = 2 * x + 3

In [110]:
C = np.array((x,y), order='C') # 行順
F = np.array((x,y), order='F') # 列順

In [111]:
C[:2].round(2)

array([[[-1.75,  0.34,  1.15, -0.25,  0.98],
        [ 0.51,  0.22, -1.07, -0.19,  0.26],
        [-0.46,  0.44, -0.58,  0.82,  0.67],
        ...,
        [-0.05,  0.14,  0.17,  0.33,  1.39],
        [ 1.02,  0.3 , -1.23, -0.68, -0.87],
        [ 0.83, -0.73,  1.03,  0.34, -0.46]],

       [[-0.5 ,  3.69,  5.31,  2.5 ,  4.96],
        [ 4.03,  3.44,  0.86,  2.62,  3.51],
        [ 2.08,  3.87,  1.83,  4.63,  4.35],
        ...,
        [ 2.9 ,  3.28,  3.33,  3.67,  5.78],
        [ 5.04,  3.6 ,  0.54,  1.65,  1.26],
        [ 4.67,  1.54,  5.06,  3.69,  2.07]]])